/**
 * Shared type definitions for TERP documentation guides
 * 
 * These types define the structure of guides generated by doc-bot
 * and consumed by the companion UI.
 */

/**
 * Metadata for a guide
 */
export interface GuideMetadata {
  /** Unique identifier for the guide (used as filename) */
  id: string;
  
  /** Human-readable title */
  title: string;
  
  /** Brief description of what the guide covers */
  description: string;
  
  /** Category for grouping guides */
  category: string;
  
  /** Tags for search and filtering */
  tags: string[];
  
  /** ISO 8601 timestamp of creation */
  createdAt: string;
  
  /** ISO 8601 timestamp of last update */
  updatedAt: string;
  
  /** Semantic version of the guide */
  version: string;
}

/**
 * A single step in a guide
 */
export interface Step {
  /** Order of this step (1-indexed) */
  order: number;
  
  /** Short title for the step */
  title: string;
  
  /** Detailed description of what to do */
  description: string;
  
  /** Filename of the screenshot (optional) */
  screenshot?: string;
  
  /** Type of action performed (for automation reference) */
  action?: 'navigate' | 'click' | 'fill' | 'select' | 'wait' | 'verify';
  
  /** CSS selector of the target element (for automation reference) */
  selector?: string;
}

/**
 * A complete guide with metadata and steps
 */
export interface Guide {
  metadata: GuideMetadata;
  steps: Step[];
}

/**
 * Search result for guide lookup
 */
export interface GuideSearchResult {
  /** The matched guide's metadata */
  guide: GuideMetadata;
  
  /** Relevance score (higher is better) */
  score: number;
  
  /** Terms that matched in the search */
  matchedTerms: string[];
}

/**
 * Validate that an object conforms to the Guide interface
 */
export function isValidGuide(obj: unknown): obj is Guide {
  if (!obj || typeof obj !== 'object') return false;
  
  const guide = obj as Guide;
  
  // Check metadata
  if (!guide.metadata || typeof guide.metadata !== 'object') return false;
  if (typeof guide.metadata.id !== 'string') return false;
  if (typeof guide.metadata.title !== 'string') return false;
  if (typeof guide.metadata.description !== 'string') return false;
  if (typeof guide.metadata.category !== 'string') return false;
  if (!Array.isArray(guide.metadata.tags)) return false;
  
  // Check steps
  if (!Array.isArray(guide.steps)) return false;
  for (const step of guide.steps) {
    if (typeof step.order !== 'number') return false;
    if (typeof step.title !== 'string') return false;
    if (typeof step.description !== 'string') return false;
  }
  
  return true;
}
