import { test, expect } from '@playwright/test';
import { captureScreenshot } from '../capture/index.js';
import { generateGuide, saveGuide } from '../guidegen/index.js';

/**
 * Example documentation flow
 * 
 * This demonstrates how to capture a workflow and generate a guide.
 * Use this as a template for creating new documentation flows.
 */
test.describe('Example Documentation Flow', () => {
  test('capture login workflow', async ({ page }) => {
    const screenshots: Array<{ path: string; title: string; description: string }> = [];
    
    // Step 1: Navigate to login page
    await page.goto('/');
    await page.waitForLoadState('domcontentloaded');
    
    const step1 = await captureScreenshot(page, { name: 'login-step-1-navigate' });
    screenshots.push({
      path: step1.path,
      title: 'Navigate to TERP',
      description: 'Open your browser and navigate to the TERP login page.',
    });
    
    // Step 2: Identify login form
    // Note: This is a template - actual selectors depend on TERP's UI
    const emailField = page.locator('input[type="email"], input[name="email"]').first();
    
    if (await emailField.isVisible()) {
      const step2 = await captureScreenshot(page, {
        name: 'login-step-2-form',
        highlight: 'input[type="email"]',
      });
      screenshots.push({
        path: step2.path,
        title: 'Locate the login form',
        description: 'Find the email and password fields on the login page.',
      });
    }
    
    // Generate guide from captured steps
    const guide = await generateGuide({
      id: 'example-login-flow',
      title: 'Example: Login to TERP',
      description: 'This is an example guide generated by doc-bot.',
      category: 'Examples',
      tags: ['example', 'login', 'template'],
      steps: screenshots.map((s, i) => ({
        title: s.title,
        description: s.description,
        screenshotPath: s.path,
      })),
    });
    
    // Save the guide
    const guidePath = await saveGuide(guide);
    console.log(`📖 Guide saved to: ${guidePath}`);
    
    // Verify guide was created
    expect(guide.steps.length).toBeGreaterThan(0);
  });
});
